[project]
name = "tparcial"
version = "0.1.0"
description = ""
authors = [
    {name = "FerTheOnePieceisReal",email = "fernanda.cruz@ucsp.edu.pe"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
]

[tool.poetry]
packages = [{include = "tparcial", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "coverage (>=7.16.2,<8.0.0)"
]
